### ISSUE TITLE
README instructions create service account that does not work

### ISSUE THREAD

**Issue by amutz** [peter-evans/nominatim-k8s#20]
Great project.  I find this extremely valuable.

One problem that I have run in to however, is that the instructions in the README for creating a service account to use in order to dump the data to the GCS bucket does not work.

I have repeatedly tried this, and each time it creates a service account that does not have access to the bucket I have created.  Whether this account is used in k8s or separately by me testing on the command line, I get these errors: service account does not have storage.objects.list access to (bucket name)

I've verified in the GCS console that the permissions should work, but they don't.  Any ideas on what I could be doing wrong here?

**Comment by peter-evans** [comment]
Glad to hear it's useful.

I've not come across this problem before. `roles/storage.objectViewer` has `storage.objects.list` permission, so I'm not sure what the issue could be. Instead of using the script, if you create the service account manually through the UI does that create an account that works for you?

**Comment by peter-evans** [comment]
Closing this for now.
